name: or_topas
channels:
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - black
  - flake8
  - glpk
  - munch
  - numpy
  - parameterized
  - pip
  - pip:
    - mpi4py
    - mpich
  - pyomo
  - pytest
  - pytest-cov
